### ISSUE TITLE
Proposal: State

### ISSUE THREAD

**Issue by arBmind** [tnt/ansible-gpg-keys-mod#1]
May you add a parameter state instead of @refresh@ and @delete@
http://docs.ansible.com/apt_module.html

possible states:
- present
- absent
- refreshed

**Comment by tnt** [comment]
This is indeed a nice idea. But the problem with refreshing is that `gpg` doesn't tell me whether or not it really refreshed the key. Maybe that is no problem. It's probably sufficient to ensure that the key is up-to-date. But when _refreshed_ is chosen it will always return _changed_ if I don't find a way to check if it got really refreshed. 

Maybe I could make use of the output of `gpg --list-keys --with-colons`... 

Sorry, I say goodnight!

**Comment by tnt** [comment]
Some tomatoes fell from my eyes. 

Maybe not the pure academic approach but seemingly sufficient to check if the key's got refreshed: I just save the output of `gpg --list-keys key` in a variable, do the same after `gpg --refresh-keys  key` and then compare the strings: `changed = before != after`.

I can reduce flow control by just passing the `module.check_mode` to `gpg` by the `--dry-run` parameter.

And the single _state_ parameter of course also simplifies the logic.

**Comment by arBmind** [comment]
sounds very reasonable :+1:

**Comment by tnt** [comment]
Yet another tomato dropped and I found a way to even predict a refresh correctly in `check_mode` which would not have worked with my yesterdays idea. (Works at least with Gnupg versions 1.4.11, 2.0.22, and 2.1.2)

The _state_-parameter works now as you proposed it.
