### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jxn** [tnt/ansible-gpg-keys-mod#11]
I wanted to fork this module (add private key import), add metadata for ansible galaxy, submit to galaxy, etc., and submit PR back to the project, but I don't know if the license will permit it.  Will you include a license and tag the repo with it, so I can know if I can fork or if I should start my own module for gpg importing?  If you have no preference, I'd recommend GPL 3.0 as that's what Ansible uses.

**Comment by tnt** [comment]
Please read line 3 of https://github.com/tnt/ansible-gpg-import-module/blob/master/gpg_import.py
