### ISSUE TITLE
Fingerprint verification

### ISSUE THREAD

**Issue by sedrubal** [tnt/ansible-gpg-keys-mod#5]
Great idea :D 

But I think there should be a variable

``` yaml
 - key_fp: "0123 4567 89AB CDEF 0123  4567 89AB CDEF 0123 4567"
```

To verify the imported key (protection against man in the middle).

**Comment by joelnb** [comment]
Wouldn't gpg check this automatically if you just specify the full fingerprint as the key id? Or are you suggesting a further check than that?

```yaml
- key_id: "0123 4567 89AB CDEF 0123  4567 89AB CDEF 0123 4567"
```

**Comment by sedrubal** [comment]
I didn't know, that you can specify keys by their full fingerprint. So this is exactly what I was looking for. Thanks.
